*
*Get-VpnConnection
Get-VpnConnectionTrigger


*Get-VMSwitch



cleart

PS C:\Users\marti\OneDrive> get-
Get-Acl
*Get-Alias
Get-AppBackgroundTask
Get-AppLockerFileInformation
Get-AppLockerPolicy
Get-AppPackage
Get-AppPackageAutoUpdateSettings
Get-AppPackageDefaultVolume
Get-AppPackageLastError
Get-AppPackageLog
Get-AppPackageManifest
Get-AppPackageVolume
Get-AppProvisionedPackage
Get-AppProvisionedSharedPackageContainer
Get-AppSharedPackageContainer
Get-AppvVirtualProcess
Get-AppxDefaultVolume
Get-AppxLastError
Get-AppxLog
Get-AppxPackage
Get-AppxPackageAutoUpdateSettings
Get-AppxPackageManifest
Get-AppxProvisionedPackage
Get-AppxVolume
Get-AssignedAccess
Get-AuthenticodeSignature
Get-AutologgerConfig
Get-BCClientConfiguration
Get-BCContentServerConfiguration
Get-BCDataCache
Get-BCDataCacheExtension
Get-BcdEntry
Get-BcdEntryDebugSettings
Get-BcdEntryHypervisorSettings
Get-BcdStore
Get-BCHashCache
Get-BCHostedCacheServerConfiguration
Get-BCNetworkConfiguration
Get-BCStatus
Get-BitLockerVolume
Get-BitsTransfer
Get-Certificate
Get-CertificateAutoEnrollmentPolicy
Get-CertificateEnrollmentPolicyServer
Get-CertificateNotificationTask
Get-ChildItem
Get-CimAssociatedInstance
Get-CimClass
Get-CimInstance
Get-CimSession
Get-CIPolicy
Get-CIPolicyIdInfo
Get-CIPolicyInfo
*Get-Clipboard
Get-ClusteredScheduledTask
Get-CmsMessage
*Get-Command
*Get-ComputerInfo
Get-Content
*Get-Counter
Get-Credential
Get-CredsFromCredentialProvider
Get-Culture
Get-DAClientExperienceConfiguration
Get-DAConnectionStatus
Get-DAEntryPointTableItem
Get-DAPolicyChange
*Get-Date
Get-DedupProperties
Get-DeliveryOptimizationLog
Get-DeliveryOptimizationLogAnalysis
Get-DeliveryOptimizationPerfSnap
Get-DeliveryOptimizationPerfSnapThisMonth
Get-DeliveryOptimizationStatus
*Get-Disk
*Get-DiskImage
Get-DiskSNV
Get-DiskStorageNodeView
Get-DnsClient
Get-DnsClientCache
Get-DnsClientDohServerAddress
Get-DnsClientGlobalSetting
Get-DnsClientNrptGlobal
Get-DnsClientNrptPolicy
Get-DnsClientNrptRule
Get-DnsClientServerAddress
Get-DOConfig
Get-DODownloadMode
Get-DOPercentageMaxBackgroundBandwidth
Get-DOPercentageMaxForegroundBandwidth
Get-DscConfiguration
Get-DscConfigurationStatus
Get-DscLocalConfigurationManager
Get-DscResource
Get-Dtc
Get-DtcAdvancedHostSetting
Get-DtcAdvancedSetting
Get-DtcClusterDefault
Get-DtcClusterTMMapping
Get-DtcDefault
Get-DtcLog
Get-DtcNetworkSetting
Get-DtcTransaction
Get-DtcTransactionsStatistics
Get-DtcTransactionsTraceSession
Get-DtcTransactionsTraceSetting
Get-Error
Get-EtwTraceProvider
Get-EtwTraceSession
Get-Event
Get-EventSubscriber
Get-ExecutionPolicy
Get-ExperimentalFeature
*Get-FileHash
*Get-FileIntegrity
*Get-FileShare
Get-FileShareAccessControlEntry
Get-FileStorageTier
*Get-FormatData
*Get-Help
Get-HgsAttestationBaselinePolicy
Get-HgsClientConfiguration
Get-HgsClientHostKey
Get-HgsGuardian
Get-HgsTrace
Get-HgsTraceFileData
Get-History
Get-HnsEndpoint
Get-HnsNamespace
Get-HnsNetwork
Get-HnsPolicyList
*Get-Host
Get-HotFix
Get-InitiatorId
Get-InitiatorPort
Get-InstalledLanguage
Get-InstalledModule
Get-InstalledScript
Get-IscsiConnection
Get-IscsiSession
Get-IscsiTarget
Get-IscsiTargetPortal
Get-IseSnippet
Get-Item
Get-ItemProperty
Get-ItemPropertyValue
Get-Job
Get-JobTrigger
Get-KdsConfiguration
Get-KdsRootKey
Get-Language
Get-LocalGroup
*Get-LocalGroupMember
*Get-LocalUser
Get-Location
Get-LogProperties
*Get-MarkdownOption
Get-MaskingSet
*Get-Member
Get-MMAgent
Get-MockDynamicParameters
Get-Module
Get-MpComputerStatus
Get-MpPerformanceReport
Get-MpPreference
Get-MpThreat
Get-MpThreatCatalog
Get-MpThreatDetection
Get-NCSIPolicyConfiguration
Get-Net6to4Configuration
*Get-NetAdapter
Get-NetAdapterAdvancedProperty
Get-NetAdapterBinding
Get-NetAdapterChecksumOffload
Get-NetAdapterDataPathConfiguration
Get-NetAdapterEncapsulatedPacketTaskOffload
Get-NetAdapterHardwareInfo
Get-NetAdapterIPsecOffload
Get-NetAdapterLso
Get-NetAdapterPacketDirect
Get-NetAdapterPowerManagement
Get-NetAdapterQos
Get-NetAdapterRdma
Get-NetAdapterRsc
Get-NetAdapterRss
Get-NetAdapterSriov
Get-NetAdapterSriovVf
Get-NetAdapterStatistics
Get-NetAdapterUso
Get-NetAdapterVmq
Get-NetAdapterVMQQueue
Get-NetAdapterVPort
Get-NetCompartment
Get-NetConnectionProfile
Get-NetDnsTransitionConfiguration
Get-NetDnsTransitionMonitoring
Get-NetEventNetworkAdapter
Get-NetEventPacketCaptureProvider
Get-NetEventProvider
Get-NetEventSession
Get-NetEventVFPProvider
Get-NetEventVmNetworkAdapter
Get-NetEventVmSwitch
Get-NetEventVmSwitchProvider
Get-NetEventWFPCaptureProvider
*Get-NetFirewallAddressFilter
Get-NetFirewallApplicationFilter
Get-NetFirewallDynamicKeywordAddress
Get-NetFirewallInterfaceFilter
Get-NetFirewallInterfaceTypeFilter
Get-NetFirewallPortFilter
Get-NetFirewallProfile
Get-NetFirewallRule
Get-NetFirewallSecurityFilter
Get-NetFirewallServiceFilter
Get-NetFirewallSetting
*Get-NetIPAddress
*Get-NetIPConfiguration
Get-NetIPHttpsConfiguration
Get-NetIPHttpsState
*Get-NetIPInterface
Get-NetIPsecDospSetting
Get-NetIPsecMainModeCryptoSet
Get-NetIPsecMainModeRule
Get-NetIPsecMainModeSA
Get-NetIPsecPhase1AuthSet
Get-NetIPsecPhase2AuthSet
Get-NetIPsecQuickModeCryptoSet
Get-NetIPsecQuickModeSA
Get-NetIPsecRule
Get-NetIPv4Protocol
Get-NetIPv6Protocol
Get-NetIsatapConfiguration
Get-NetLbfoTeam
Get-NetLbfoTeamMember
Get-NetLbfoTeamNic
*Get-NetNat
Get-NetNatExternalAddress
Get-NetNatGlobal
Get-NetNatSession
Get-NetNatStaticMapping
Get-NetNatTransitionConfiguration
Get-NetNatTransitionMonitoring
*Get-NetNeighbor
Get-NetOffloadGlobalSetting
Get-NetPrefixPolicy
Get-NetQosPolicy
Get-NetRoute
Get-NetSwitchTeam
Get-NetSwitchTeamMember
*Get-NetTCPConnection
*Get-NetTCPSetting
Get-NetTeredoConfiguration
Get-NetTeredoState
Get-NetTransportFilter
Get-NetUDPEndpoint
Get-NetUDPSetting
*Get-NetView
*Get-NetworkSwitchEthernetPort
Get-NetworkSwitchFeature
Get-NetworkSwitchGlobalData
Get-NetworkSwitchVlan
Get-NonRemovableAppsPolicy
Get-OdbcDriver
Get-OdbcDsn
Get-OdbcPerfCounter
Get-OffloadDataTransferSetting
Get-OperationValidation
Get-Package
Get-PackageProvider
Get-PackageSource
Get-Partition
Get-PartitionSupportedSize
Get-PcsvDevice
Get-PcsvDeviceLog
Get-PfxCertificate
Get-PfxData
Get-PhysicalDisk
Get-PhysicalDiskSNV
Get-PhysicalDiskStorageNodeView
Get-PhysicalExtent
Get-PhysicalExtentAssociation
Get-PmemDedicatedMemory
Get-PmemDisk
Get-PmemPhysicalDevice
Get-PmemUnusedRegion
Get-PnpDevice
Get-PnpDeviceProperty
Get-PreferredLanguage
Get-PrintConfiguration
Get-Printer
Get-PrinterDriver
Get-PrinterPort
Get-PrinterProperty
Get-PrintJob

get-process
Get-Process -Id 14424
Get-Process -name ema*

bug if  narrow term:
####get-process| findstr 5396

###get-process | findstr 14424
###get-process | findstr -i ema
###get-process | findstr 14






Get-ProcessMitigation
Get-ProvisionedAppPackage
Get-ProvisionedAppSharedPackageContainer
Get-ProvisionedAppxPackage
Get-ProvisioningPackage
Get-PSBreakpoint
Get-PSCallStack
Get-PSDrive
Get-PSHostProcessInfo
Get-PSProvider
Get-PSReadLineKeyHandler
Get-PSReadLineOption
Get-PSRepository
Get-PSSession
Get-PSSessionCapability
Get-PSSessionConfiguration
Get-Random
Get-ResiliencySetting
Get-Runspace
Get-RunspaceDebug
Get-ScheduledJob
Get-ScheduledJobOption
Get-ScheduledTask
Get-ScheduledTaskInfo
Get-SecureBootPolicy
Get-SecureBootUEFI
Get-Service
Get-SmbBandWidthLimit
Get-SmbClientConfiguration
Get-SmbClientNetworkInterface
Get-SmbConnection
Get-SmbDelegation
Get-SmbGlobalMapping
Get-SmbMapping
Get-SmbMultichannelConnection
Get-SmbMultichannelConstraint
Get-SmbOpenFile
Get-SmbServerCertificateMapping
Get-SmbServerCertProps
Get-SmbServerConfiguration
Get-SmbServerNetworkInterface
Get-SmbSession
Get-SmbShare
Get-SmbShareAccess
Get-SmbWitnessClient
Get-StartApps
Get-StorageAdvancedProperty
Get-StorageBusBinding
Get-StorageBusCache
Get-StorageBusClientDevice
Get-StorageBusDisk
Get-StorageBusTargetCacheStore
Get-StorageBusTargetCacheStoresInstance
Get-StorageBusTargetDevice
Get-StorageBusTargetDeviceInstance
Get-StorageChassis
Get-StorageDataCollection
Get-StorageDiagnosticInfo
Get-StorageEnclosure
Get-StorageEnclosureSNV
Get-StorageEnclosureStorageNodeView
Get-StorageEnclosureVendorData
Get-StorageExtendedStatus
Get-StorageFaultDomain
Get-StorageFileServer
Get-StorageFirmwareInformation
Get-StorageHealthAction
Get-StorageHealthReport
Get-StorageHealthSetting
Get-StorageHistory
Get-StorageJob
Get-StorageNode
Get-StoragePool
Get-StorageProvider
Get-StorageRack
Get-StorageReliabilityCounter
Get-StorageScaleUnit
Get-StorageSetting
Get-StorageSite
Get-StorageSubSystem
Get-StorageTier
Get-StorageTierSupportedSize
Get-SupportedClusterSizes
Get-SupportedFileSystems
Get-SystemDriver
Get-SystemLanguage
Get-SystemPreferredUILanguage
Get-TargetPort
Get-TargetPortal
Get-TestDriveItem
Get-TimeZone
Get-TlsCipherSuite
Get-TlsEccCurve
Get-Tpm
Get-TpmEndorsementKeyInfo
Get-TpmSupportedFeature
Get-TraceSource
Get-TroubleshootingPack
Get-TrustedProvisioningCertificate
Get-TypeData
Get-UICulture
*Get-Unique
Get-Uptime
Get-Variable
*Get-Verb
Get-VHD
Get-VHDSet
Get-VHDSnapshot
Get-VirtualDisk
Get-VirtualDiskSupportedSize
Get-VM
Get-VMAssignableDevice
Get-VMBios
Get-VMCheckpoint
Get-VMComPort
Get-VMConnectAccess
Get-VMDirectVirtualDisk
Get-VMDvdDrive
Get-VMFibreChannelHba
Get-VMFirmware
Get-VMFloppyDiskDrive
Get-VMGpuPartitionAdapter
Get-VMGroup
Get-VMHardDiskDrive
Get-VMHost
Get-VMHostAssignableDevice
Get-VMHostCluster
Get-VMHostNumaNode
Get-VMHostNumaNodeStatus
Get-VMHostPartitionableGpu
Get-VMHostSupportedVersion
Get-VMIdeController
Get-VMIntegrationService
Get-VMKeyProtector
Get-VMKeyStorageDrive
Get-VMMemory
Get-VMMigrationNetwork
*Get-VMNetworkAdapter
Get-VMNetworkAdapterAcl
Get-VMNetworkAdapterExtendedAcl
Get-VMNetworkAdapterFailoverConfiguration
Get-VMNetworkAdapterIsolation
Get-VMNetworkAdapterRdma
Get-VMNetworkAdapterRoutingDomainMapping
Get-VMNetworkAdapterTeamMapping
Get-VMNetworkAdapterVlan
Get-VMPartitionableGpu
Get-VMPmemController
Get-VMProcessor
Get-VMRemoteFx3dVideoAdapter
Get-VMRemoteFXPhysicalVideoAdapter
Get-VMReplication
Get-VMReplicationAuthorizationEntry
Get-VMReplicationServer
Get-VMResourcePool
Get-VMSan
Get-VMScsiController
Get-VMSecurity
Get-VMSnapshot
Get-VMStoragePath
Get-VMStorageSettings
Get-VMSwitch
*Get-VMSwitchExtension
Get-VMSwitchExtensionPortData
Get-VMSwitchExtensionPortFeature
Get-VMSwitchExtensionSwitchData
Get-VMSwitchExtensionSwitchFeature
Get-VMSwitchTeam
Get-VMSystemSwitchExtension
Get-VMSystemSwitchExtensionPortFeature
Get-VMSystemSwitchExtensionSwitchFeature
Get-VMVideo
Get-Volume
Get-VolumeCorruptionCount
Get-VolumeScrubPolicy
*Get-VpnConnection
Get-VpnConnectionTrigger
Get-WdacBidTrace
Get-WheaMemoryPolicy
Get-WIMBootEntry
Get-WinAcceptLanguageFromLanguageListOptOut
Get-WinCultureFromLanguageListOptOut
Get-WinDefaultInputMethodOverride
Get-WindowsCapability
Get-WindowsDeveloperLicense
Get-WindowsDriver
Get-WindowsEdition
Get-WindowsErrorReporting
Get-WindowsImage
Get-WindowsImageContent
Get-WindowsOptionalFeature
Get-WindowsPackage
Get-WindowsReservedStorageState
Get-WindowsSearchSetting
Get-WindowsUpdateLog
Get-WinEvent
Get-WinHomeLocation
Get-WinhttpProxy
Get-WinLanguageBarOption
Get-WinSystemLocale
Get-WinUILanguageOverride
Get-WinUserLanguageList
Get-WSManCredSSP
Get-WSManInstance
PS C:\Users\marti\OneDrive> get-

