# f8_text_file
# (an f8_text_file is-not meant to be run as a whole)
)
exit

# (selected lines from this file can be run in a terminal ... e.g. by the F8 key, customly bound to runSelectedText  )

echo '-------- section --------'


 (eepitch-eshell)
 (eepitch-kill)
 (eepitch-eshell)

cmd
 powershell
  pwsh
   node -i
    .exit












C:\Users\marti\OneDrive\eev-f8\w32.e.el

file:///C:\Users\marti\OneDrive\eev-f8\msys2-problem--msys2-cmd.f8.ps1

