
https://copy.sh/v86/?profile=windows98

command

doskey

cd c:\windows

dir *.exe /s /b /l /on >com1

doskey /?
doskey /h
###doskey /h >com1 hang



This is the serial console. Whatever you type or paste here will be sent to COM1sfsf
c:\windows\accstat.exe
c:\windows\arp.exe
c:\windows\asd.exe
c:\windows\calc.exe
c:\windows\cdplayer.exe
c:\windows\charmap.exe
c:\windows\cleanmgr.exe
c:\windows\clipbrd.exe
c:\windows\clspack.exe
c:\windows\control.exe
c:\windows\cvt1.exe
c:\windows\cvtaplog.exe
c:\windows\defrag.exe
c:\windows\dialer.exe
c:\windows\dosrep.exe
c:\windows\drwatson.exe
c:\windows\emm386.exe
c:\windows\explorer.exe
c:\windows\extrac32.exe
c:\windows\fontview.exe
c:\windows\freecell.exe
c:\windows\ftp.exe
c:\windows\grpconv.exe
c:\windows\hh.exe
c:\windows\hwinfo.exe
c:\windows\ipconfig.exe
c:\windows\jview.exe
c:\windows\kodakimg.exe
c:\windows\kodakprv.exe
c:\windows\mm2ent.exe
c:\windows\mplayer.exe
c:\windows\mshearts.exe
c:\windows\msncreat.exe
c:\windows\msnmgsr1.exe
c:\windows\nbtstat.exe
c:\windows\net.exe
c:\windows\netdde.exe
c:\windows\netstat.exe
c:\windows\netwatch.exe
c:\windows\notepad.exe
c:\windows\packager.exe
c:\windows\pbrush.exe
c:\windows\pidset.exe
c:\windows\ping.exe
c:\windows\progman.exe
c:\windows\protman.exe
c:\windows\regedit.exe
c:\windows\rg2catdb.exe
c:\windows\route.exe
c:\windows\rsrcmtr.exe
c:\windows\rundll.exe
c:\windows\rundll32.exe
c:\windows\scandskw.exe
c:\windows\scanregw.exe
c:\windows\setdebug.exe
c:\windows\setver.exe
c:\windows\sigverif.exe
c:\windows\smartdrv.exe
c:\windows\sndrec32.exe
c:\windows\sndvol32.exe
c:\windows\sol.exe
c:\windows\sysmon.exe
c:\windows\taskman.exe
c:\windows\taskmon.exe
c:\windows\telnet.exe
c:\windows\tour98.exe
c:\windows\tracert.exe
c:\windows\tuneup.exe
c:\windows\twunk_16.exe
c:\windows\twunk_32.exe
c:\windows\upwizun.exe
c:\windows\vcmui.exe
c:\windows\welcome.exe
c:\windows\winfile.exe
c:\windows\winhelp.exe
c:\windows\winhlp32.exe
c:\windows\wininit.exe
c:\windows\winipcfg.exe
c:\windows\winmine.exe
c:\windows\winpopup.exe
c:\windows\winrep.exe
c:\windows\winver.exe
c:\windows\wjview.exe
c:\windows\write.exe
c:\windows\wscript.exe
c:\windows\wupdmgr.exe
c:\windows\application data\microsoft\welcome\weldata.exe
c:\windows\command\attrib.exe
c:\windows\command\chkdsk.exe
c:\windows\command\cscript.exe
c:\windows\command\cvt.exe
c:\windows\command\debug.exe
c:\windows\command\deltree.exe
c:\windows\command\extract.exe
c:\windows\command\fc.exe
c:\windows\command\fdisk.exe
c:\windows\command\find.exe
c:\windows\command\iextract.exe
c:\windows\command\label.exe
c:\windows\command\mem.exe
c:\windows\command\move.exe
c:\windows\command\mscdex.exe
c:\windows\command\nlsfunc.exe
c:\windows\command\scandisk.exe
c:\windows\command\scanreg.exe
c:\windows\command\sort.exe
c:\windows\command\start.exe
c:\windows\command\subst.exe
c:\windows\command\sulfnbk.exe
c:\windows\command\xcopy.exe
c:\windows\command\xcopy32.exe
c:\windows\desktop\sheep.exe
c:\windows\system\actmovie.exe
c:\windows\system\addreg.exe
c:\windows\system\awfxex32.exe
c:\windows\system\bpcpost.exe
c:\windows\system\cfgwiz32.exe
c:\windows\system\cliconfg.exe
c:\windows\system\cmdl32.exe
c:\windows\system\cmmgr32.exe
c:\windows\system\cmmon32.exe
c:\windows\system\cmstp.exe
c:\windows\system\conagent.exe
c:\windows\system\ddhelp.exe
c:\windows\system\dllhost.exe
c:\windows\system\dplaysvr.exe
c:\windows\system\dsssig.exe
c:\windows\system\dxdiag.exe
c:\windows\system\esserver.exe
c:\windows\system\fixmapi.exe
c:\windows\system\fontreg.exe
c:\windows\system\gdi.exe
c:\windows\system\icwscrpt.exe
c:\windows\system\ie4uinit.exe
c:\windows\system\ieshwiz.exe
c:\windows\system\imgstart.exe
c:\windows\system\internat.exe
c:\windows\system\jdbgmgr.exe
c:\windows\system\krnl386.exe
c:\windows\system\lights.exe
c:\windows\system\lmscript.exe
c:\windows\system\loadwc.exe
c:\windows\system\locproxy.exe
c:\windows\system\locprxy2.exe
c:\windows\system\mkcompat.exe
c:\windows\system\mnmsrvc.exe
c:\windows\system\mobsync.exe
c:\windows\system\mprexe.exe
c:\windows\system\msconfig.exe
c:\windows\system\msgsrv32.exe
c:\windows\system\mshta.exe
c:\windows\system\mstask.exe
c:\windows\system\mstinit.exe
c:\windows\system\odbcad32.exe
c:\windows\system\odbcconf.exe
c:\windows\system\pstores.exe
c:\windows\system\redir32.exe
c:\windows\system\regsvr32.exe
c:\windows\system\regwiz.exe
c:\windows\system\rnaapp.exe
c:\windows\system\rpcss.exe
c:\windows\system\rsvp.exe
c:\windows\system\runonce.exe
c:\windows\system\sage.exe
c:\windows\system\sfc.exe
c:\windows\system\spool32.exe
c:\windows\system\stimon.exe
c:\windows\system\sucatreg.exe
c:\windows\system\sysedit.exe
c:\windows\system\systray.exe
c:\windows\system\tapi16.exe
c:\windows\system\tapiini.exe
c:\windows\system\tapisrv.exe
c:\windows\system\tapiupr.exe
c:\windows\system\tcmsetup.exe
c:\windows\system\tlocmgr.exe
c:\windows\system\unam4ie.exe
c:\windows\system\user.exe
c:\windows\system\walign.exe
c:\windows\system\wmiexe.exe
c:\windows\system\wsasrv.exe
c:\windows\system\macromed\director\m5drvr32.exe
c:\windows\system\oobe\msoobe.exe
c:\windows\system\viewers\quikview.exe


